# [Info]
site_name: LearningWeb3.0 # 左上角标题
site_url: https://github.com/sonichen/LearningWeb3.0
site_author: Soni
site_description: Learning Web3.0

# [Navigtion]
nav:
  - Home: index.html
  - 基础知识:
      - 概念:
        - 基础知识/概念/以太坊原理书.md
        - 精通以太坊:
          - 基础知识/概念/精通以太坊/1.什么是以太坊.md
      - Solidity:
        - 基础知识/Solidity/0.Solidity.md
        - 基础知识/Solidity/1.FirstContract.md
        - 基础知识/Solidity/2.Varibale.md
        - 基础知识/Solidity/3.VariableType.md
        - 基础知识/Solidity/4.Constants.md
        - 基础知识/Solidity/5.Immutable.md
        - 基础知识/Solidity/6.EtherANDWei.md
        - 基础知识/Solidity/7.Gas.md
        - 基础知识/Solidity/8.IfElse.md
        - 基础知识/Solidity/9.Loop.md
        - 基础知识/Solidity/10.Mapping.md
        - 基础知识/Solidity/11.Array.md
        - 基础知识/Solidity/12.Enum.md
        - 基础知识/Solidity/13.struct.md
        - 基础知识/Solidity/14.DataLocations.md
        - 基础知识/Solidity/15.Function.md
        - 基础知识/Solidity/16.FunctionModifier.md
        - 基础知识/Solidity/17.Events.md
        - 基础知识/Solidity/18.Constructor.md
        - 基础知识/Solidity/19.Inheritance.md
        - 基础知识/Solidity/20.Visibility.md
        - 基础知识/Solidity/21.Interface.md
        - 基础知识/Solidity/22.Error.md
        - 基础知识/Solidity/23.DeployAnyContract.md
        - 基础知识/Solidity/24.this.md
        - 基础知识/Solidity/25.接收ETH.md
        - 基础知识/Solidity/26.SendETH.md
  - Project:
      - Project/Rust实现区块链/Rust实现区块链.md
  - 阅读:
      - 阅读/从架构维度看Web2.0与Web3.0应用之别.md
# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: dark # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: light
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url:  https://github.com/sonichen/LearningWeb3.0 
repo_name:  LearningWeb3.0 
## [bottom-left corner]
copyright: sonichen # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/sonichen/LearningWeb3.0
      name: GitHub | LearningWeb3.0

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols

 